version: "3.8"
services:
  database-dev-env:
    build: .
    depends_on:
      - postgres
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
      - ~/.aws:/home/vscode/.aws
    command: /bin/sh -c "while sleep 1000; do :; done"
  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
    # https://geshan.com.np/blog/2021/12/docker-postgres/
    # https://github.com/docker-library/docs/tree/master/postgres#initialization-scripts
      - dbdata:/var/lib/postgresql/data
      - devenv-init-scripts/01-init.sh:/docker-entrypoint-initdb.d/01-init-user-db.sh
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: finalproject_devcontainer_adminer # fix for duplicate container instance error
    restart: always
    ports:
      - 8080:8080
volumes:
  dbdata:
