version: "3.8"
services:
  postgres:
    image: postgres:13.1
    container_name: finalproject_devenv_postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: finalproject_devenv_adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdbdata:
